/* config.h for HP700 / HP-UX / cc */

/* the following section was generated by repchk */
typedef int rml_sint_t;
typedef unsigned int rml_uint_t;
#define RML_LOG2_SIZE_INT 2
#define RML_SIZE_INT 4
#define RML_SIZE_DBL 8
#define RML_DBL_PAD
#define RML_DBL_STRICT
#define RML_STACK_GROWS_POSITIVE
/* end of repchk-generated section */

#define	RML_CLOCK_TIMES

#define RML_ALLOCA_EMULATE

#define rml_setjmp	_setjmp
#define rml_longjmp	_longjmp

#ifdef	RML_PLAIN
#define RML_YOUNG_SIZE	(32*1024)
#endif
#ifdef	RML_SWITCH
#define RML_YOUNG_SIZE	(48*1024)
#endif

#ifdef	RML_PLAIN
#define RML_STATE_JOIN
#endif
#ifdef	RML_SWITCH
#define	RML_STATE_JOIN
#endif
